include(FetchContent)

string(TOUPPER ${CMAKE_FIND_PACKAGE_NAME} upper_find_package_name)

if(CMODULE_SHARED_LIBS OR CMODULE_${upper_find_package_name}_SHARED_LIB)
  set(CMODULE_SHARED_LIB YES)
  set(CMODULE_STATIC_LIB NO)
  set(CMODULE_LIB_TYPE "SHARED")
else()
  set(CMODULE_SHARED_LIB NO)
  set(CMODULE_STATIC_LIB YES)
  set(CMODULE_LIB_TYPE "STATIC")
endif()

set_property(GLOBAL PROPERTY USE_FOLDERS ON)

if(IOS)
  set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
endif()

macro(cmodule_set_local_options)
  set(cmodule_cmake_folder_backup ${CMAKE_FOLDER})
  get_property(cmodule_compile_options_backup DIRECTORY PROPERTY COMPILE_OPTIONS)

  set(CMAKE_FOLDER "cmodule")
  if(CMODULE_DISABLE_WARNINGS)
    if(${CMAKE_CXX_COMPILER_ID} STREQUAL MSVC)
      add_compile_options(/W0)
    else()
      add_compile_options(-w)
    endif()
  endif()
endmacro()

macro(cmodule_restore_local_options)
  set(CMAKE_FOLDER ${cmodule_cmake_folder_backup})
  set_property(DIRECTORY PROPERTY COMPILE_OPTIONS ${cmodule_compile_options_backup})
endmacro()

macro(cmodule_select_target shared static)
  if(CMODULE_SHARED_LIB)
    set(CMODULE_TARGET ${shared})
  else()
    set(CMODULE_TARGET ${static})
  endif()
endmacro()

function(cmodule_get_content_version)
  unset(version)
  foreach(arg IN LISTS ARGN)
    if(version)
      string(REPLACE "=" "_" arg2 ${arg})
      set(version "${version}_${arg2}")
      set(content_version ${version} PARENT_SCOPE)
      return()
    elseif(arg STREQUAL "URL_HASH")
      set(version "hash")
    elseif(arg STREQUAL "GIT_TAG")
      set(version "git")
    elseif(arg STREQUAL "SVN_REVISION")
      set(version "svn")
    endif()
  endforeach()
endfunction()

function(cmodule_add name version)
  cmodule_get_content_version(${ARGN})
  set(content_name ${name}-${version}-${content_version})
  set(content_source_dir "")

  if(CMODULE_CACHE_SOURCE_DIR)
    set(source_dir ${CMODULE_CACHE_SOURCE_DIR}/${name}/${version}-${content_version})
    file(LOCK ${source_dir}.lock)
    string(TOUPPER ${content_name} upper_content_name)
    if (NOT FETCHCONTENT_SOURCE_DIR_${upper_content_name})
      file(GLOB source_dir_files ${source_dir}/*)
      if (source_dir_files)
        set(FETCHCONTENT_SOURCE_DIR_${upper_content_name} ${source_dir})
      else()
        set(content_source_dir SOURCE_DIR ${source_dir})
      endif()
    endif()
  endif()

  FetchContent_Declare(
    ${content_name}
    ${content_source_dir}
    ${ARGN}
  )

  FetchContent_GetProperties(${content_name})
  string(TOLOWER ${content_name} lower_content_name)
  if(NOT ${lower_content_name}_POPULATED)
    FetchContent_Populate(${content_name})
    if(EXISTS "${${lower_content_name}_SOURCE_DIR}/CMakeLists.txt")
      cmodule_set_local_options()
      add_subdirectory("${${lower_content_name}_SOURCE_DIR}" "${${lower_content_name}_BINARY_DIR}" EXCLUDE_FROM_ALL)
      cmodule_restore_local_options()
    endif()
  endif()

  if(CMODULE_CACHE_SOURCE_DIR)
    file(LOCK ${source_dir}.lock RELEASE)
  endif()

  set(CMODULE_${name}_SOURCE_DIR ${${lower_content_name}_SOURCE_DIR} PARENT_SCOPE)
  set(CMODULE_${name}_BINARY_DIR ${${lower_content_name}_BINARY_DIR} PARENT_SCOPE)

  string(TOUPPER ${CMAKE_FIND_PACKAGE_NAME} upper_find_package_name)
  set(${upper_find_package_name}_FOUND TRUE PARENT_SCOPE)
  set(${CMAKE_FIND_PACKAGE_NAME}_FOUND TRUE PARENT_SCOPE)
endfunction()
